// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductProject.API.Contexts;

namespace ProductProject.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductProject.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("ProductType");

                    b.Property<int>("State");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2022, 9, 7, 18, 39, 3, 672, DateTimeKind.Utc), Description = "The one with that big park.", ProductType = 0, State = 0, Value = 100m },
                        new { Id = 2, Date = new DateTime(2022, 9, 7, 18, 39, 3, 672, DateTimeKind.Utc), Description = "The one with the cathedral that was never really finished.", ProductType = 0, State = 0, Value = 200m },
                        new { Id = 3, Date = new DateTime(2022, 9, 7, 18, 39, 3, 672, DateTimeKind.Utc), Description = "The one with that big tower.", ProductType = 0, State = 0, Value = 300m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
